### PR TITLE
Updated Persian (FA) voices

### PR DESCRIPTION
**Pull request by xmha97**
Removed blank space within voices

### CODE REVIEW

**Comment by vshcherb** [comment]
Could you please test it?

**Comment by xmha97** [comment]
> 
> 
> Could you please test it?

Yes, I tested it on the way home today and it worked well.

**Comment by xmha97** [comment]
https://youtu.be/cRoWPvTep4k

**Comment by xmha97** [comment]
@vshcherb Do you intend to merge these changes?

**Comment by vshcherb** [comment]
they are already merged

**Comment by xmha97** [comment]
But it's not available in the OsmAnd app and the old voice are still downloaded.

**Pull request merged**
