### PR TITLE
Fix lt_tts.js by replacing "let" into "var"

### PR DESCRIPTION
**Pull request by embar-**
Otherwise Lithuanian TTS may not work in OsmAnd

### CODE REVIEW

**Comment by embar-** [comment]
Thanks. Can you please rebuild Lithuanian TTS voice package and 
distribute it? The fixed version is still not visible via OsmAnd mobile 
application...

**Comment by vshcherb** [comment]
Migrated to 4.8 branch, nightly 4.9 is available already

**Comment by embar-** [comment]
I see now that language packages are different for OsmAnd versions...
Thanks for backporting to v4.8.
Can you please backport this fix to v4.7 also?

**Comment by vshcherb** [comment]
Nope 4.7 is frozen for us and we're not going to produce any builds any more

**Comment by embar-** [comment]
We need re-package LT voice package with "recorded OGG audio files", not only "single TTS" package.

**Comment by vshcherb** [comment]
@sonora will later do it

**Comment by sonora** [comment]
Done.

**Comment by embar-** [comment]
2024-08-01 18:40, Hardy rašė:
> Done.


I just opened OsmAnd 4.8 and still don't see update for Lithuanian voice.

I also downloaded 
https://download.osmand.net/download?standard=yes&file=lt_0.voice.zip 
and it's date is 2024-05-08 - outdated.

**Pull request merged**
