### PR TITLE
fr : rephrasing of "Location lost/recovered" to "Localisation perdue/retrouvée"

### PR DESCRIPTION
**Pull request by breversa**
"Location lost/recovered" was previously translated to "GPS signal lost/recovered".

However :
- GPS is only one of the several existing satellite positionning systems (GLONASS, Beidou, later Galileo) 
- Satellite positionning is not the only existing positionning : cell towers, wifi hotspots, later Bluetooth and other technologies (RFID/NFC tags ?) can be used as well
- Location can be lost even though GPS signal (or signals) has not been lost

For those reasons, I propose a more correct translation of "Localisation perdue/retrouvée"

Also :
- disambiguation of "serrez/restez"
- "route_calculate.ogg" is played when calculation is over, hence "Itinéraire recalculé"

### CODE REVIEW

**Comment by vshcherb** [comment]
This pull-request will not changed recorded files and these files should not be modified manually

**Comment by breversa** [comment]
That's what I feared.

What should be done then ?

2016-03-11 17:37 GMT+01:00 vshcherb <notifications@github.com>:

**Comment by vshcherb** [comment]
Not much we don't have possibility to regeneeate ispeech voice, so we need to fully regneerate voice package then.

**Comment by breversa** [comment]
Thanks for your reply, but I don't get it. :-/

What IS possible, and what ISN'T ?

2016-03-12 19:39 GMT+01:00 vshcherb <notifications@github.com>:

**Comment by vshcherb** [comment]
Without regeneration of all voice recordings, it is not possible today. We don't have regeneration setup.

**Comment by breversa** [comment]
So basically, we used to have that capability, but no longer ? How come ?

2016-03-14 13:42 GMT+01:00 vshcherb <notifications@github.com>:

**Pull request closed without merging**
