### PR TITLE
Voice-only guidance files for Sardinian (sc)

### PR DESCRIPTION
**Pull request by l2212**
I couldn't find any tts engine that supports this language, right now.

### CODE REVIEW

**Comment by vshcherb** [comment]
What language engine did you use ?

**Comment by l2212** [comment]
Balabolka with an italian voice, Microsoft Elsa Desktop (the one most "compatible" with Sardinian) and adapting the input words to try to obtain the correct sounds.

**Comment by vshcherb** [comment]
My only question would be how we are going to support new sounds in case, will it be ok to contact you if there are some tiny changes? If that's ok could you please put in comment somewhere that information what's been used.

**Comment by l2212** [comment]
For me it's fine, I think. For information you mean my e-mail account?

l2212scr@yahoo.it

**Comment by vshcherb** [comment]
I hope I could reach via Github and you check at least once per 3-4 months if main tts english file has changed.
Thanks for contribution!

**Comment by l2212** [comment]
Ok, I will try to remember it. Thanks to you for your great work!

**Comment by l2212** [comment]
Hello @vshcherb ,
one Sardinian University created a prototype, with some Sardinian voices for MARY TTS:

http://sintesa.eu/en/prototipo/

Could that be fine? Does OsmAnd supports that engine?

**Comment by sonora** [comment]
Based of these comments https://github.com/marytts/marytts/issues/318 it should be possible - definitely worth a try.

**Comment by l2212** [comment]
@sonora Cool! What should I do?

**Comment by l2212** [comment]
Also, I've seen that the voice files are still not in the "downloads" list. Why?

**Pull request merged**
