### PR TITLE
Update phrases.xml

### PR DESCRIPTION
**Pull request by dktzde**
corrected German: Fahrgemeinschaft -> Carsharing Standort

### CODE REVIEW

**Comment by xmd5a2** [comment]
There is an easier way to translate. Use https://hosted.weblate.org/projects/osmand/

**Comment by xmd5a2** [comment]
Besides, this is not original file, just a copy for development purposes

**Comment by dktzde** [comment]
Thanx a lot - but I cannot find the string on weblate. So I will give up now to correct the misleading translation. (maybe you can help?)
see also: https://github.com/osmandapp/Osmand/issues/1517

**Comment by xmd5a2** [comment]
See https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values-de/phrases.xml
This is correct and actual file.

**Comment by dktzde** [comment]
Thanx!

**Pull request merged**
