### PR TITLE
Update zh-tw voice.

### PR DESCRIPTION
**Pull request by s8321414**
I updated zh-tw voice, please review and merge it :smiley:

### CODE REVIEW

**Comment by vshcherb** [comment]
it is on hold cause we're going to reimplement cause we had some issues

**Comment by s8321414** [comment]
BTW, could you generate .ogg for zh-tw? I don't have prolog on my distribution Orz.

**Comment by vshcherb** [comment]
uf... :-) I'm not sure if I could generate it cause now we don't use prolog anymore and it is javascript, so it is an old procedure

**Comment by s8321414** [comment]
OK :-)

**Comment by vshcherb** [comment]
@s8321414   now it is ready :-)

**Comment by s8321414** [comment]
> @s8321414 now it is ready :-)

Errr... for what?

**Comment by vshcherb** [comment]
Now it is possible to add turn_exit (https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/en_tts.js#L287) and give it a try. It is an optional funciton

**Comment by s8321414** [comment]
> Now it is possible to add turn_exit (https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/en_tts.js#L287) and give it a try. It is an optional funciton

Can't you sync them to all languages? :P

**Comment by vshcherb** [comment]
@s8321414 do you think the order of words is legitimate?

**Comment by s8321414** [comment]
> @s8321414 do you think the order of words is legitimate?

looks good :smile:

**Comment by s8321414** [comment]
So you can sync them, I just don't want to open a PR to do this :S

**Pull request closed without merging**
