### PR TITLE
 Nautical render INT-1 J K, add night mode shaders and shields

### PR DESCRIPTION
**Pull request by josail**
- add nightMode shaders
- add nichtMode icon shields
- adjust nautical.render.xml accordingly
- improved versions of weed and sea_wave icons
- correct naming error for shaders in nautical.render.xml
- correct logical error for lines as edges pf seabed area rocky and coral, display is now in line with cliffs on land, and as similar as currently possible to INT-1 J21 J22
- correct display again tested with OffRoad.jar

### CODE REVIEW

**Review by josail — COMMENTED** [review]
I don't really understand the cause of conflict for merging. Double checking the changes indicated in github shows me that all changes seem ok and as intended, especially in nautical.render.xml.

**Comment by xmd5a2** [comment]
I've made some corrections after previous PR was merged. https://github.com/osmandapp/OsmAnd-resources/commit/0e4835ff8a0e129f63c771d97a7fa1fae7388ba7
Looks like this is the cause.

**Comment by josail** [comment]
Will you be able to resolve this? Please let me know, if I shall support from my side. The resolve button is not available for me.

The intention of renaming was to have a consistent naming for the seamark icons, shaders and shields including their reference in the International Nautical Chart No 1 (INT-1). The names of the files provide for consistent referencing in the nautical.render.xml by following scheme: seamark_L##_name, where L is the INT-1 section letter and ## is the corresponding number (leaving out the . seperator, so that 13.2 is equal to 132, which is still unique, as all other INT-1 numbers are <99)

**Comment by xmd5a2** [comment]
This should be fixed in this PR. You should git pull from master branch and reapply your changes.

**Comment by josail** [comment]
Commit ' e6d230e' seems to work now without conflicts: 
I have optimisedthe svg and again produced all new png files with the 'generatepng.sh' and 'sortfiles.sh' tools. 
Rebasing my fork has pulled your earlier commit '216a84c' and I guess it was that what was missing in my PR? or some other problem, which was resolved by the file optimisationa and reproduction.

**Comment by josail** [comment]
OffRoad_nautical_render_xml_test

**Pull request merged**
