### PR TITLE
Deleted space after comma,  in italian it is wrong

### PR DESCRIPTION
**Pull request by mircozorzo**

### CODE REVIEW

**Comment by sonora** [comment]
Mirco, can you please explain which text you hear pronounced wrong in Italian? The deletion you made here just separates the string name and the string content, it has nothing to do with what you hear.

**Comment by mircozorzo** [comment]
Hi Hardy, thank you for the reply.

The announce is perfect, but the notification on the toast in the top of
the screen that summarize the route appear with a space between the
distance and the comma, is not a big error but it's surely an error. Space
it's ok after the comma but it's always an error before.

2017-01-04 18:58 GMT+01:00 Hardy <notifications@github.com>:

**Comment by sonora** [comment]
Hello Mirco, can you produce a screenshot? What you describe sounds like it needs fixing in all languages, but I am not 100% sure I know what you are talking about ... - Thx!

**Comment by mircozorzo** [comment]
Hi Hardy, it's attached in this and also in the previous message. I'm
talking about the space after the unit of distance ("chilometri" in
Italian) and before the comma.

Thanks

Mirco

2017-01-06 13:45 GMT+01:00 Hardy <notifications@github.com>:

**Comment by sonora** [comment]
Mirco, just t be sure: Your Pull request removes the space after the comma in this line: `string('time.ogg', 'il tempo è ').` This does not change anything visible in OsmAnd, this space simply separates the file name (`time.ogg`) and its value (`il tempo è `) in the config file syntax.

Can you produce a screenshot or explain how you get to the exact OsmAnd screen where the actual error you observe is displayed?  Thx!

**Comment by mircozorzo** [comment]
Yes, in I receive this notification (once the route is calculated), on a
android 5.1.1 with interface Emui 3.1 lite, in the top bar notification
toast area.

So my intention is to remove the gap/space between "chilometri" and the
comma so the string will become "chilometri, il ..." and not "chilometri ,
il ..."

Thank you, Mirco

[image: Immagine incorporata 1]

2017-01-07 23:10 GMT+01:00 Hardy <notifications@github.com>:

**Comment by aceman444** [comment]
Yes, the patch seems strange and should not affect anything being displayed or spoken via TTS in OsmAnd. If you are after he space you need to look at the 'chilometri ' (note the space before ending quote) string on another line.

**Comment by sonora** [comment]
Now I see what you mean. Point is that the tts confg files were originally designed to get pronunciation right, but it looks like recently we also use them to **display** some of their text. Will need to look into this. May also be related to #3368, not sure yet.

**Comment by sonora** [comment]
@mircozorzo  I think I now fixed what you meant here, can you please test? Thanks!

**Comment by mircozorzo** [comment]
Thank you Hardy, it's better nearly good, but it isn't really a big
problem. This on 6.6.0#20090M

Mirco



​

2017-01-11 9:45 GMT+01:00 Hardy <notifications@github.com>:

**Comment by sonora** [comment]
Hello Mirco,

do you still see the issue? I would have thought I had caught it all (did it for all languages, which was a lot of work).

If you still see occurrences, can you please post an example sentence here (in the original language)?

Thx - Hardy

I

**Pull request merged**
