### PR TITLE
Grammer and pronounciation corrections

### PR DESCRIPTION
**Pull request by madanadam**
Corrected grammer errors and  order at sentences

### CODE REVIEW

**Comment by sonora** [comment]
Hi, thanks for working on this!

It looks like this is a massive change, both to wording and grammar. Was the previous so bad that this should replace it? Or is this maybe some regional variant or alternative we should somehow name and have in addition?

**Comment by madanadam** [comment]
It was weird to listen in Turkish especially road names. So I want to change order of words. I wonder who did previous translation? Because it was incorrect in Turkish. I live in Turkey and my main language is Turkish. After this corrections I will change other files Turkish files

**Comment by sonora** [comment]
Ok, thanks!

**Comment by sonora** [comment]
PS: You have added many leading or trailing blanks in the dictionary section, I believe these are all obsolete. I had explicitly added needed separators to all TTS' grammar sections many months ago.

**Comment by madanadam** [comment]
Its because of my editor i think :)

**Comment by sonora** [comment]
I've cleaned it up for you. If there is anything not as expected, please let me know here, ok?

**Comment by madanadam** [comment]
Thanks a lot. I'll pay more attention to spaces in my other works.

**Pull request merged**
