### PR TITLE
add Slovak

### PR DESCRIPTION
**Pull request by Evgenij27**

### CODE REVIEW

**Comment by aceman444** [comment]
Hi, is this an automatic conversion of ttsconfig.p from prolog to JS, without logical changes? If so, thank you for doing it. Is this now the primary format and new changes should be done on this file?

**Comment by PaulStets** [comment]
@aceman444 Hi, we have converted the old Prolog files to JavaScript manually trying to preserve the logic. Feel free to edit the file if you notice any mistakes. Starting from the next update we'll be using JS instead of Prolog. You can already test the new engine in the nightly version. We'll be more than glad if you could test it and send us the feedback.

**Comment by aceman444** [comment]
So in OsmAnd 3.1 the Prolog version is still used, but in 3.2 (and nighlties) the JS version is used?

**Comment by PaulStets** [comment]
Yes, you can still switch between the two in the Development settings. When you upgrade to the new version, the js files will be downloaded automatically.

**Pull request merged**
