### PR TITLE
reduce penalty transition

### PR DESCRIPTION
**Pull request by Evgenij27**

### CODE REVIEW

**Comment by aceman444** [comment]
Why? Does this tiny change cause any specific change in routing?

**Comment by maraf24** [comment]
Even slight change can affect routing, but it would be good to know what real problem does this solve.

**Comment by vshcherb** [comment]
There should be a test introduced and the link to bug which is pretty obvious.

**Comment by vshcherb** [comment]
Moved to https://github.com/osmandapp/OsmAnd-resources/pull/529/files

**Pull request merged**
