### PR TITLE
Fix time(Sec) for all languages

### PR DESCRIPTION
**Pull request by vmonkey**
All languages should be fixed. I was not however sure with 'ja', so I added the fix only for the TTS.

### CODE REVIEW

**Comment by aceman444** [comment]
What is this doing? :)

**Comment by aceman444** [comment]
Is it when there is an exact number of hours and 0 minutes?

**Comment by aceman444** [comment]
grr, it is written in the commit message to each file :)

**Comment by vshcherb** [comment]
Thanks

**Pull request merged**
