### PR TITLE
Allow shuttle trains

### PR DESCRIPTION
**Pull request by ionum**
Create new option to avoid shuttle trains (similar to ferries)

Resolves https://github.com/osmandapp/Osmand/issues/1308

### CODE REVIEW

**Comment by aceman444** [comment]
There are only 18 uses of shuttle_train in the whole OSM world. Also, there is no wiki page about how to use it. How do you know the routing over it actually works correctly?

**Comment by ionum** [comment]
I tested it. It generally works. There may be only 18 shuttle_trains, but they are important ways in their regions. OSRM and other routing engines already use it.

If you want to test it:

From the mainland to the island of Sylt, connected by the Hindenburgdamm, only by train and foot (Germany, Schleswig-Holstein)
From Kandersteg to Brig (Switzerland)
From Brig to Domodossola (Switzerland & Italy Piemont)

BTW: Option "Avoid shuttle_train" has to be translated. I can deliver german & french. How can I help

**Comment by aceman444** [comment]
So if the trains are important, can you create the wiki page so that everybody knows how to tag them. Then everybody can also see why OsmAnd is doing what it is doing now with them :)

**Comment by ionum** [comment]
See http://wiki.openstreetmap.org/wiki/Proposed_features/shuttle_train

**Comment by aceman444** [comment]
Nice, thanks. Maybe you can now add OsmAnd to the list on that page :)

**Comment by ionum** [comment]
Done

**Pull request merged**
