### PR TITLE
Add rendering of Low Emission Zones

### PR DESCRIPTION
**Pull request by pietervdvn**
This PR implements the _rendering_ of Low Emission Zones.

Low Emission zones are now included into the 'rendering_types' for obf creation and are rendered with the existing 'grey_diagonal'-shader.

I'm not entirely sure about the exact rendering at the moment. Initially, I wanted to print 'LEZ' over the area (similar to 'NR' for Nature Reserve), but I couldn't figure out how to build OsmAnd with the NDK - so my personal build can't render polygons :(.

So, if you guys are happy with the rendering, remove the 'LEZ'-asset alltogether. If not, please include it into the nightly builds and I'll experiment with it further.

The current rendering is the grey 'diagonal', although a sparser version could be used too.

This PR is related to https://github.com/osmandapp/Osmand/issues/4922 and https://github.com/osmandapp/Osmand/issues/6427 .

PS: I've also added the names to a few categories in rendering, namely category `club`, `craft` and `administrative_boundary`. AFAIK this has no effect.

Screenshot_20190407-001004_OsmAnd~
Screenshot_20190407-000952_OsmAnd~
Screenshot_20190407-000943_OsmAnd~

### CODE REVIEW

**Comment by aceman444** [comment]
Hi, why the space in  name="craft " ?

**Comment by pietervdvn** [comment]
That was a typo - I've removed that space. Thanks for pointing out.

**Comment by vshcherb** [comment]
We are working on this PR to get it merged to 3.4 and we've realized that we need to properly handle low_emission_zone multipolygon. We've also thinking about different color cause in different cities there are 1-3 levels of low_emission_zone.

**Comment by pietervdvn** [comment]
Allright, cool!

I'll see it pop up in OsmAnd sooner or later.
Also, very cool that my previous PRs are in the production version now - it gives me quite some bragging rights <3

**Comment by pietervdvn** [comment]
As this branch is semimerged with the upstream, the PR can be closed.

**Pull request closed without merging**
