### PR TITLE
Fix mistake last update

### PR DESCRIPTION
**Pull request by OpenSourceForEver**
Fix double  [+ " " +"]

https://github.com/osmandapp/OsmAnd-resources/pull/576#issuecomment-516141105

Thanks to @aceman444

### CODE REVIEW

**Comment by OpenSourceForEver** [comment]
By the way, what do you think about the change introduced in https://github.com/osmandapp/OsmAnd-resources/pull/576 to do it also in other languages ​​such as English?

**Comment by aceman444** [comment]
I'm not sure. While it is good to have short and concise voice commands, they must be clear to the driver. Each language must make that sure on its own. Not say "enter" (the roundabout) may be ambiguous whether to enter the roundabout or just take a branch right before it.

**Comment by OpenSourceForEver** [comment]
For example "at the roundabout take the second exit" would be clear enought. My englis is not very good but I think "At the roundabout" can not be considered outside the roundabout.

**Comment by aceman444** [comment]
There may be subtle differences even in English, 'at' may not be the right word, 'on' or 'in' could be even better.

**Pull request merged**
