### PR TITLE
INT-1, K Obstructions, J Seabed, Weed, Seagrass 

### PR DESCRIPTION
**Pull request by josail**
Adding nautical rendering for seamarks in INT-1 section K Obstructions and J Seabed, Weed, Seagrass, following latest amendment of OpenNauticalChart and OpenSeaMap rendering.
See especiall: https://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_J

OsmAnd nautical.render.xml version 1.1 2021-12-22 was adjusted to shortened icon and shader file names and includes
all related resized .svg files for seamark_j and seamark_k icons and shaders in folders \icons\svg\seamark and \icons\svg\shaders, correspondingly. The .svg files have not yet been generated as .png files with the tool generatepng.sh and need sorting to the right folders by sortfiles.sh. Thanks for further support in achieving  this!

The nautical.render.xml includes renderingProperty options for seabedDetail as nameTag2: 
simple=1st surface type as letters according to INT-1 J1-J13, 
category=surface tag in seamark_category, 
all=surface qualification and type included in seabed_surface_all, seagrass and weed in seabed_taxon_all including category, genus and taxon, 
omit=no display

Befor adjustemnt of filenames version 1.1 2021-12-18 has been tested in OffRoad.jar by combination of version 1.1 of rendering_types.xml and version 1.1 of nautical.renderer.xml, e.g. http://osmand.net/go.html?lat=36.65161&lon=25.37019&z=16, feedback welcome: josail @ gmx.de

Intended rendering of seabed detail according to INT-1 section K and J:
2ndPullRequest_2021_12_22

### CODE REVIEW

**Comment by josail** [comment]
file list for sortfile.sh (please double check, whether this is correct syntax), corresponding .svg files are located in \icons\svg\seamark:
icon seamark_j132_weedkelp
icon seamark_j134_seagrass
icon seamark_j14_sand_waves
icon seamark_j15_spring
icon seamark_j21_rocky_path
icon seamark_j22_coral_path
icon seamark_k311_foul_ground

procedure/syntax for shaders is not completely clear for me, here is the list of related files in \icons\svg\shaders:
h_j132_weedkelp_shader.svg
h_j134_seagrass_shader.svg
h_j14_sand_waves_shader.svg
h_j20_stonesgravel.svg
h_j2122_rockycoral.svg

**Comment by xmd5a2** [comment]
Icons should be described like this
`icon_alias seamark_seabed_area_surface_coral seamark_coral`
icon_alias png_name svgdir_svgname
Shaders are processed automatically if in `generated.sh` folder is described as   # genMapIconsNoScale 'shaders'
And you should uncomment required folders to process them.

**Comment by josail** [comment]
Following this instruction leads to partial success. I continue to run into a problem when running 'generate.sh', i.e. the rsvg-convert command is not found (although I made a fresh install of git-bash. The icons/vd/svg and icons/vd/map folders are filled with the new icons and shaders in vector formats (svg and xml). However, the icons/png subfolders remain completely empty. So it is the first part of the procedure with rsvg-convert for png's that does not work. Do I have to load/install the rsvg-convert command/executable somehow?

Here is the first part of the echo output of 'generatepng_int1.sh', which I just renamed for my editing: 
Rj@PC1116 MINGW64 /c/rj/Github/osmand-resources/icons/tools (master)
$ bash generatepng_int1.sh
shaders_int1
generatepng_int1.sh: line 51: rsvg-convert: command not found
generatepng_int1.sh: line 52: rsvg-convert: command not found
generatepng_int1.sh: line 53: rsvg-convert: command not found
generatepng_int1.sh: line 54: rsvg-convert: command not found
generatepng_int1.sh: line 51: rsvg-convert: command not found
generatepng_int1.sh: line 52: rsvg-convert: command not found
generatepng_int1.sh: line 53: rsvg-convert: command not found
generatepng_int1.sh: line 54: rsvg-convert: command not found
generatepng_int1.sh: line 51: rsvg-convert: command not found
generatepng_int1.sh: line 52: rsvg-convert: command not found
generatepng_int1.sh: line 53: rsvg-convert: command not found
generatepng_int1.sh: line 54: rsvg-convert: command not found
generatepng_int1.sh: line 51: rsvg-convert: command not found
generatepng_int1.sh: line 52: rsvg-convert: command not found
generatepng_int1.sh: line 53: rsvg-convert: command not found
generatepng_int1.sh: line 54: rsvg-convert: command not found
generatepng_int1.sh: line 51: rsvg-convert: command not found
generatepng_int1.sh: line 52: rsvg-convert: command not found
generatepng_int1.sh: line 53: rsvg-convert: command not found
generatepng_int1.sh: line 54: rsvg-convert: command not found
-c parsed, so we will convert the SVG files
-in parsed C:\rj\Github\osmand-resources\icons\vd\svg
-out parsed C:\rj\Github\osmand-resources\icons\vd\map

**Comment by xmd5a2** [comment]
Of course you have to install rsvg-convert

**Comment by josail** [comment]
Hi xmd5a2, merry Christmas, thanks for your helpful hints.
Above there is a little present. That was not so easy without admin rights on my first computer, but finally I managed to install rsvg-convert and to produce all png icons and shaders on a second computer. They look realy very good and sharp. So rsvg-convert is really the right tool to do it. Please double check and let me know if something would be missing.  Best regards, Jo

**Comment by xmd5a2** [comment]
Hi. Merry Christmas! have you checked this PR in night mode?

**Comment by josail** [comment]
Hi xmd5a,

I have checked night mode compatability so far as 

that old „opaque shields“ for mud and coral/rock weed/sand were not applied in night mode in the past and I maintained this and made this behavior now specific for these three old shaders. But it is no longer applied to the other shaders, so that they should indeed render in night mode. 

 For the new shaders according to INT-1 I think that weed (dark brown) and seagrass (dark green) can readily be applied in night mode.

For the J2122 rocky or coral polygon shader it is in a light brown colour and again suitable and implemented without restriction for night mode. 

Surface letters (INT-1 J1 to J11) are in dark blue and ok, I think. 

But I did not find a night mode switch in the OffRoad software for double checking.

For the black icons and shades (J14 sandwaves, J15 spring, J20 stones and gravel, I do not know the right solution? But I could easily change the colours of the icons and the shader. 

Please let me know, what colour would Work best or is commonly used for iriginally black icons in night mode and I will be able to add svg and png icons accordingly in that hex colour. 

J21 rocky edges (path) and J22 coral edges (path) have I think a principle status „under development“ in OsmAnd. Meanwhile the thin grey line rendering is a good preliminary solution both for day and night mode. I would be happy to learn, how the path pattern, which copies INT-1 J21 and J22 patterns, could become visible in OsmAnd.

I will be happy to contribute as I can to make this work. As the syntax and rendering concepts are quite complex, it is good to have concrete hints from you to get it done together. 

Also the night mode itself, I tried to infer the necessary specification from the past version of nautical.render.xml as good as I can. If there is any more explicit document on night mode concepts, please share it with me. 

Viele Grüsse 

Jo

Am 27.12.2021 um 08:34 schrieb xmd5a ***@***.***>:

﻿
Hi. Merry Christmas! have you checked this PR in night mode?

**Comment by josail** [comment]
for the adjusted night mode behaviour see restriction to three old shaders as it has been in the past

in file nautical.render.xml lines 3329 to 3334 : 

				<apply_if additional="seamark:seabed_area:surface=sand" shader="sand_opaque"/>
				<apply_if additional="seamark:seabed_area:surface=weed;sand" shader="weed_sand_opaque"/> 
				<apply_if additional="seamark:seabed_area:surface=mud" shader="mud2_opaque"/>
				<apply_if additional="seamark:seabed_area:surface=sand" nightMode="true" shader=""/> 
				 
				<apply_if additional="seamark:seabed_area:surface=weed;sand" nightMode="true" shader=""/>
				<apply_if additional="seamark:seabed_area:surface=mud" nightMode="true" shader=""/>

**Comment by xmd5a2** [comment]
It is much better like this:
```
<apply_if additional="seamark:seabed_area:surface=weed;sand" shader="weed_sand_opaque"> 
            <apply_if nightMode="true" shader=""/>
</apply>
```

**Comment by xmd5a2** [comment]
Usually we use semitransparent light icon shields (or shaders) for night mode. Or do not render shaders at all.

**Comment by josail** [comment]
The shaders are all designed with transparent background, so they are already semi-transparent, in which the coloured lines of the drawings in the shader are in front of transparent area. Non of the new icons should appear with white or blue background. This is also true for the sand_waves. Only for this J14 sand_waves I will have to change the icon displayed in the https://wiki.openstreetmap.org/wiki/Main_Page
Which I will do in a minute…

**Comment by josail** [comment]
This was the old general solution for the opaque shaders, which I maintained for them. I could live with it, if you like to keep it also for all other quite transparent shaders with thin line drawing.

 

However I think that night mode should continue to highlight rock and coral, sandwaves as potential dangers and allow information on weed and seagrass, foul ground for trageting the right spot for anchoring.

 

Nevertheless, i have picked the idea and the original xml line now again at the very bottom of the switch in line 3341, allowing to omit seabed shading by the option "seabedDetail=omit":

<switch minzoom="14">

     <case ...

     ...

    <apply_if seabedDetail="omit" shader="" color="#76cbea" />
</switch>

 

Is this ok in your view? I think it would achieve what you wrote below by dedicated choice "omit". But I'm happy if you decide in context whether it is necessary to also have and add

 

   <apply_if nightMode="true" shader=""/>

 

 

at the end of the same shader switch. It would then avoid any information from polygons in "night mode".

 


Gesendet: Montag, 27. Dezember 2021 um 11:17 Uhr
Von: "xmd5a" ***@***.***>
An: "osmandapp/OsmAnd-resources" ***@***.***>
Cc: "Jo" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [osmandapp/OsmAnd-resources] INT-1, K Obstructions, J Seabed, Weed, Seagrass (PR #760)


 

It is much better like this:

<apply_if additional="seamark:seabed_area:surface=weed;sand" shader="weed_sand_opaque">
            <apply_if nightMode="true" shader=""/>
</apply>

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/0e4835ff8a0e129f63c771d97a7fa1fae7388ba7

**Pull request merged**
