### PR TITLE
New: Horsebackriding

### PR DESCRIPTION
**Pull request by derfuessl**
Add Routing for Horsebackriding

OSMand would be the ideal navigation system for horse riding as all the necessary data is contained in OSM.
There are currently no comparable navigation systems on the market.

### CODE REVIEW

**Comment by vshcherb** [comment]
Looks cool and interesting

**Comment by vshcherb** [comment]
Did you participate any Telegram chat / discussing specific about development?

**Comment by derfuessl** [comment]
No. Not yet. I just found the import routing.xml option in the OSMand-App last week an started directly to make one for riding. Since I have a bit experience in programming and used OSM a lot, making the xml was not so hard.I was looking for something like this for some time. I have tried the xml File and was very happy whit the results. (One additional option for the rendering would be nice, but this is for another day ;-) ) After looking for a suitable program for a long time, I wanted to share my results.And make the option of an (German) Translation for the Parameter in Profile.
-------- Ursprüngliche Nachricht --------Von: vshcherb ***@***.***> Datum: 07.09.21  21:09  (GMT+01:00) An: osmandapp/OsmAnd-resources ***@***.***> Cc: derfuessl ***@***.***>, Author ***@***.***> Betreff: Re: [osmandapp/OsmAnd-resources] New: Horsebackriding (#713) 
Did you participate any Telegram chat / discussing specific about development?

**Comment by vshcherb** [comment]
Sounds cool, CC @sonora @xmd5a2

**Pull request merged**
